#!/bin/bash

# Run make command to build paper.pdf
make paper.pdf

# Check the exit status of the make command
if [ $? -ne 0 ]; then
    echo "Error: Make command failed. Aborting commit."
    exit 1
fi
