name: Proselint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Proselint
        uses: docker://your-proselint-image:latest
